travis:
  secure:
    BINSTAR_TOKEN: JmEVBXd/7rhny/adm92Q+LybQLNaikcSRZKyQS1GSwbdKhmxXnKPZ9ctYt2EWkFgeW8+DnwfrZRq1MwvnMyICeZk1bvAyMVBhYVOQ13qRxZezfytnxq5KTrPw/I4ziL5I9dLYKlBkR46F4XAhfdVCXkKpiHhf+NeYgmmwYSCzGqpQRtAx91hLb9wwa+B2XRDPvlKupI76vkojd9CIXNcdrNmfESR8BckXGsQ96AO5Dyy/33/mFLYtIqxbud9CU8piAfv33nF/QtFEYBVu0jhM8Zy1fUfKkF3SVr0wv/OzaDbyG79bBQ7t0FecwBMwa+35sO3axChR806u82u/2vgcJmkLBFn5aZMRtQeAtr5b2DvrZl2Nhj3u6thrTE7/W7y8gLX1r75yoeXdT++HFuQ2HiA7ugx0jvt2U3/WFwunU5YSCOY+BEFhDgZI1tKLeub/V6IBOa/8RwIlFcg6O8Rwg2EhpsjQD5s/urW2wnssoesDkFAk5yawFjY0aOe/MC556JCZStedoNa/b232HC+fiKNYr2WxG5uDyf4zqBdDRTribjs1e+McbyMD00WDubF9jcs7Ur+AYU5NCf8duXmu9T+8RtiRmg9EyPrzvCKfZLn6/R83L970ZW4MgttB/UIZwmTAVb/lzmBm7g5ay92v9Ky1lrGAXA/F1nezAi2Ozw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
