travis:
  secure:
    BINSTAR_TOKEN: woW7CpWEiEDlPxSP1GD56i3YaUcGw+L6U9hfjeJwmawBW5FRzBxnVt60HoYQQ62oPw69KipQKuRFKuzovGc7BzDHBGPp3VOAnmzQPSDd/ei+bzZ7yVObmhL86qtI8pyy+E2PCSISRiPX7PxOk0BItIaeca5VTtzhYLMVO/3Q9oRq4CTfDBIcxjoOy9Ut81Ll4yFTKzkhaA3d0PxngYm8k2BHgsZzL/r68Jqoir7FGgSRrzbK26UFDJT8dE8RhTFguDI0LmldnLqOD35GUcqnZ4IOVioSsER+zq6GdQrGkNNwcgBvfs9mpW51WRyUI3Ege1bupuRpFO2514W8cFDY+uOFfhr0E/gTpgsw76cgFguJ9GRriFlDZBojK4tkOShNLhm7PJr7sGDRfgi6EG8eDKbg/t9376SQ1Rs/GBLA4ECmAMdp8l3kBa0TjEIMmvbu/pLxAofNKmfpbd63AFWYPq/XlEAv5WPfyUJZQ+n84Mh6dIkwk0Jb5UM5Tu0jIHEJ2lEco+rvH3Z6X8QojfBxRKFCCc4IkaeLVLGJMzF5wMx+zhYKqZrAVpJ9Ea4+fMtDVAsM0vIoscyonqX5OlCtWpe2VizDw2JhNw3fzFUfm5J8uMcHma/ojeRpFbgRlcaoZnMqRCzquf6qgKT5fSIgS4adtx82wUJaOlEdfNFYvxw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
