travis:
  secure:
    BINSTAR_TOKEN: uQMADcQxRIFdDs8OrzgqOB28B79yGqvU9VHeLRD/TqDPuyAkH9EAb2RZ07t9kOItwZtDVOLxQq47gox1I5kha004uQxGThHFffc73lzE0aYrfmEhTxr6sxiSHU2LCT6GPS7f/IEbOaTVQJ1udlpQ5NowmhheiitJyhg6a4wu/fL9YN5m+ty3Ga/wbikxs+g9U91rtEC88xsut6pwOT5jIQjnVA5QCcGzuol3N9wh/A8OThvMMYV0T0lqFVKUl27X0TKVvF0Q56qyztuW8SYjEd9USc/ut6Jv4rCklkPhl5OdJTNiVeuh2fkswenVVhPXb0qo9Y9kTphMEK/tUmBP9DpBSz0k7oNlUULiiFR8kcfUl/NCmKKQIjXeIBJOy1tMOhfu0umBnDmHilIrz3UbrPLBEv8SQjqWKwfcW8vLPkJYLjIB4XWd6j0QAZY1dEaPMndn1aEgnvFdAJdjMKuxjGBVeiQDnUr1LvVM5VTByWq+fokBHX9uoTF8PMILW3kL5o8n2ieYGC2PT8hig2BjiWlGs2KCrFT4MxihtVFGuxpOfd0yQYovD/TKj0rBFPdOgt3LNZnTw4K+Fl/zuA83rSyC+g0IwdxrONmjgpHy1YiTF7C+m/x+Fy05TjUO7MplY6jBWZ3bGlQqrzngvnWoRkeMSSJQoLUyPa/ZWi7bFTA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
